### ISSUE TITLE
Improve ado validation resiliency and error message

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#3135]
```[tasklist]
### Tasks
- [x] If we fail to connect to ADO with an error that seems transient (ex: `Exception: System.Net.Http.HttpRequestException: No such host is known. (dev.azure.com:443) ---> System.Net.Sockets.SocketException (11001): No such host is known.`), we should retry a couple of times.
- [x] Create and return a new general 'ado connection failed' error when the issue is not authentication based
- [x] Handle case where PAT is valid but scopes are wrong
```

https://github.com/microsoft/onefuzz/blob/be56814e439f43f8a312940f14fc6f040d1994c5/src/ApiService/ApiService/onefuzzlib/notifications/Ado.cs#L72-L80

[AB#152444](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/152444)

**Comment by Porges** [comment]
We should also pool `VssConnection` since it does a sign-in and is `IDisposable`.
